### ISSUE TITLE
Add support for creating subdirectories

### ISSUE THREAD

**Issue by freitagdavid** [ivaano/NsxLibraryManager#16]
I just found your app, and I must say it's really great loving the design, and multi-platform support.

The issue I'm running into is in the renamer if you have a sub directory added to your output the renamer fails. I'm guessing this just wasn't a usecase for you so it slipped by. I like to organize my games like `{BasePath}/{TitleName}/{TitleName}`, `{BasePath}/{TitleName}/DLC/{TitleName}`, etc.

Here's the error I received.

```
NsxLibraryManager.Core.Services.RenamerService[0]
      Error renaming file D:\NsxLibrary-win-x64-0.2.0\library\some title name\some title name [0010000][v0].nsz - Could not find a part of the path.
      ```

**Comment by ivaano** [comment]
I think what's missing is the path creation, but it can added easily I think I'll add this on the next release

**Comment by ivaano** [comment]
New Release [#v0.3.0](https://github.com/ivaano/NsxLibraryManager/releases/tag/v0.3.0) is available, now the app will  create folders if you use them in your template, just a heads up for DLC it should be `{BasePath}/{AppName}/DLC/{TitleName}`
