### ISSUE TITLE
Using 'Saving configuration' saves config.json in \NsxLibraryManager-win-x64-0.3.0\ instead of \NsxLibraryManager-win-x64-0.3.0\titledb\

### ISSUE THREAD

**Issue by grimson73** [ivaano/NsxLibraryManager#19]
Hi there, thanks for developing this software.

When first starting the app the config.json is created here:
\NsxLibraryManager-win-x64-0.3.0\titledb\config.json

Then the defaults warning box is displayed and then I started to modify the path and select recursive.
When saving and reloading the app the settings weren't maintained.

I noticed that saving the config creates and modifies the config.json on this location:
\NsxLibraryManager-win-x64-0.3.0\config.json.

So I guess the save function does save the config.json on the 'wrong' location and isn't used like you mentioned to use the \titledb\  folder for the config.json.

Thanks! :)

**Comment by ivaano** [comment]
Please use new release https://github.com/ivaano/NsxLibraryManager/releases/tag/v0.3.1 it should save on the config folder now.
