### ISSUE TITLE
Error getting package info

### ISSUE THREAD

**Issue by TheRealNextria** [ivaano/NsxLibraryManager#30]
Hello, 

I am running the Library manager, and getting a the error below.
 dotnet 8.0 is installed, am i doing something wrong ?

Content root path: C:\Users\bosro\Desktop\NsxLibraryManager-win-x64-0.3.1\NsxLibraryManager-win-x64-0.3.1
fail: NsxLibraryManager.Core.Services.FileInfoService[0]
      Error getting package info
      NsxLibraryManager.Core.Exceptions.FileNotSupportedException: Unable to determine the package type of the file.
         at NsxLibraryManager.Core.FileLoading.PackageInfoLoader.GetPackageInfo(String filePath, Boolean detailed) in C:\Users\Ivan\RiderProjects\NsxLibraryManager\NsxLibraryManager.Core\FileLoading\PackageInfoLoader.cs:line 33

Also i have with some games like "Where Angels Cry" i have the latest update v196608 (version 3).
But in the list of missing updates it show under availible update "131072 - [2]".
i tried reloading and refreshing and redownloading the version.json but i still keep getting it.

Hope you can help me.
![Untitled](https://github.com/ivaano/NsxLibraryManager/assets/89243308/6795967e-6343-487d-845e-fe7909b75583)
![Untitled1](https://github.com/ivaano/NsxLibraryManager/assets/89243308/cc55d088-0c57-40bd-9af0-fb1392f12988)

**Comment by ivaano** [comment]
Do you have your keys in the right place? this error means 2 things, the file is not a valid nsp, or the keys are not working to decrypt the file. I will be adding a more clear description for this errors
