### ISSUE TITLE
Add file filter while scanning directories: Currently all filetypes are added to library

### ISSUE THREAD

**Issue by duracotton** [ivaano/NsxLibraryManager#36]
If I refresh my library and also have files like .pdf (artbooks) or .nfo files in there it will add them to the tool's library:

![grafik](https://github.com/ivaano/NsxLibraryManager/assets/25416153/18943979-262a-42a6-9ca5-98b545ca7a00)

Solution: Add a file filter for *.nsp, *.nsz, *xci, *xcz and ignore all other types while scanning file directories.

**Comment by ivaano** [comment]
This is already implemented and is set to be out in the next release, I'm preparing a beta release because it has a lot of changes.
